#!/bin/bash

pushd "$(dirname "${0}")"

pushd "./payload"
tar cf ../payload.tar ./*
popd  # ./payload

if [ -e "payload.tar" ]; then
	gzip payload.tar

	if [ -e "payload.tar.gz" ]; then
		cat decompress payload.tar.gz > selfextract.bash
	else
		echo "payload.tar.gz does not exist"
		exit 1
	fi
else
	echo "payload.tar does not exist"
	exit 1
fi

echo "selfextract.bash created"

